const constants = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    LOGIN_FORM_VISIBILITY: "LOGIN_FORM_VISIBILITY",
    IS_AUTHENTICATED: "IS_AUTHENTICATED",
    LOGING_IN: "LOGING_IN",
    AUTHENTICATION_ERROR_MESSAGE: "AUTHENTICATION_ERROR_MESSAGE",
    RETRIEVE_APPLICATIONS: "RETRIEVE_APPLICATIONS",
    ADD_APPLICATION: "ADD_APPLICATION",
    RETRIEVE_SELECTED_APPLICATIONS: "RETRIEVE_SELECTED_APPLICATIONS",
    ADD_APPLICATION_FORM_VISIBILITY: "ADD_APPLICATION_FORM_VISIBILITY",
    HAS_ERROR_ON_ADDING_APPLICATION: "HAS_ERROR_ON_ADDING_APPLICATION",
    SELECT_APPLICATION_ENTRY: "SELECT_APPLICATION_ENTRY",
    UNSELECT_APPLICATION_ENTRY: "UNSELECT_APPLICATION_ENTRY"
}

export default constants