const constants = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    LOGIN_FORM_VISIBILITY: "LOGIN_FORM_VISIBILITY",
    IS_AUTHENTICATED: "IS_AUTHENTICATED",
    AUTHENTICATION_ERROR_MESSAGE: "AUTHENTICATION_ERROR_MESSAGE"
}

export default constants